[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.4",
    "streamlit>=1.47.1",
    "trafilatura>=2.0.0",
    "validators>=0.35.0",
]
